### ISSUE TITLE
Try writing it in Java and I can contribute

### ISSUE THREAD

**Issue by tarifrr** [shahadul-17/HTTP-Streaming-Server#1]
Try writing it in Java and I can contribute
--Tarif

**Comment by shahadul-17** [comment]
Sir I've committed the Java based implementation. You can now contribute...

Note: This server currently works with Windows Media Player and HTML5 player but does not work with VLC Media Player. You can try this server using Windows Media Player. To do so,

(1) Run the **Server** and make sure you have your **media-file** in your **Project Root Directory**.
(2) Open **Windows Media Player** and press **"CTRL + U"** and type **"http://your-ip-address:port/media-file.mp4"** and click **OK button** (your ip-address and port number will be shown in the **Server Console**).
